swipe:
  3:
    left: 
      command: 'xdotool key alt+shift+Tab'
    right: 
      command: 'xdotool key alt+Tab'
    up: 
      command: 'xdotool key ctrl+alt+Down'
    down: 
      command: 'xdotool key ctrl+alt+Up'
  4:
    left: 
      command: 'xdotool key ctrl+shift+Tab'
    right: 
      command: 'xdotool key ctrl+Tab'
    up: 
      command: 'xdotool key ctrl+alt+shift+Down'
    down: 
      command: 'xdotool key ctrl+alt+shift+Up'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1

